### ISSUE TITLE
Running Windows having this type of error

### ISSUE THREAD

**Issue by akgada** [bhoominn/nb_utils#6]
D:\Portfolio\Project\auto_localization_maker\windows\flutter\generated_plugin_registrant.cc(13,3): error C3861: 'nb_utils_pluginRegisterWithRegistrar': identifier not found [D:\Portfolio\Project\auto_localization_maker\build\windows\runner\auto_localization_maker.vcxproj]
Exception: Build process failed.

**Comment by rockyprabowo** [comment]
You can use my fork for now. 
Replace nb_utils definition with this on your pubspec.yaml.
```yaml
dependencies:
    nb_utils:
        git:
            url: git://github.com/rockyprabowo/nb_utils.git
            ref: 1e936ea56f263ce1c93da64fe6ba7aba7a76fe4a
```
